package com.isoftstone.kaoqin.bean;

public class Project {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_name
     *
     * @mbggenerated
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_type
     *
     * @mbggenerated
     */
    private String projectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_state
     *
     * @mbggenerated
     */
    private Integer projectState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.id
     *
     * @return the value of project.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.id
     *
     * @param id the value for project.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_name
     *
     * @return the value of project.project_name
     *
     * @mbggenerated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_name
     *
     * @param projectName the value for project.project_name
     *
     * @mbggenerated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_type
     *
     * @return the value of project.project_type
     *
     * @mbggenerated
     */
    public String getProjectType() {
        return projectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_type
     *
     * @param projectType the value for project.project_type
     *
     * @mbggenerated
     */
    public void setProjectType(String projectType) {
        this.projectType = projectType == null ? null : projectType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_state
     *
     * @return the value of project.project_state
     *
     * @mbggenerated
     */
    public Integer getProjectState() {
        return projectState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_state
     *
     * @param projectState the value for project.project_state
     *
     * @mbggenerated
     */
    public void setProjectState(Integer projectState) {
        this.projectState = projectState;
    }
}